name       : haskell-libxml-sax
version    : 0.7.5
release    : 3
source     :
    - http://hackage.haskell.org/package/libxml-sax-0.7.5/libxml-sax-0.7.5.tar.gz : 99141784cc0d6c5749f0df618b2d46922391eede09f4f9ccfc36fb58a9c16d51
license    : MIT
component  : programming.haskell
summary    : Bindings for the libXML2 SAX interface
description: |
    Bindings for the libXML2 SAX interface
builddeps  :
    - haskell-cabal-install
    - haskell-xml-types-devel
rundeps    :
    - devel:
        - haskell-xml-types-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
